# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_2/ULTRA96V2.srcs/sources_1/bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_3/ULTRA96V2_auto_pc_3.xci
# IP: The module: 'ULTRA96V2_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_2/ULTRA96V2.srcs/sources_1/bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_3/ULTRA96V2_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ULTRA96V2_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_2/ULTRA96V2.srcs/sources_1/bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_3/ULTRA96V2_auto_pc_3.xci
# IP: The module: 'ULTRA96V2_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_2/ULTRA96V2.srcs/sources_1/bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_3/ULTRA96V2_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ULTRA96V2_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
