# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ULTRA96V2/ultra96v2_oob.xdc

# Block Designs: bd/ULTRA96V2/ULTRA96V2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2 || ORIG_REF_NAME==ULTRA96V2} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_zynq_ultra_ps_e_0_0/ULTRA96V2_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ULTRA96V2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xbar_0/ULTRA96V2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xbar_0 || ORIG_REF_NAME==ULTRA96V2_xbar_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_interconnect_0_0/ULTRA96V2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_interconnect_0_0 || ORIG_REF_NAME==ULTRA96V2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_0_0/ULTRA96V2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_0_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_bram_ctrl_0_0/ULTRA96V2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ULTRA96V2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_blk_mem_gen_0_0/ULTRA96V2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_blk_mem_gen_0_0 || ORIG_REF_NAME==ULTRA96V2_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_uart16550_0_0/ULTRA96V2_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_uart16550_0_0 || ORIG_REF_NAME==ULTRA96V2_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_uart16550_1_0/ULTRA96V2_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_uart16550_1_0 || ORIG_REF_NAME==ULTRA96V2_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_gpio_0_0/ULTRA96V2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_gpio_0_0 || ORIG_REF_NAME==ULTRA96V2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_gpio_1_0/ULTRA96V2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_gpio_1_0 || ORIG_REF_NAME==ULTRA96V2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_gpio_2_0/ULTRA96V2_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_gpio_2_0 || ORIG_REF_NAME==ULTRA96V2_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_PWM_w_Int_0_0/ULTRA96V2_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_PWM_w_Int_0_0 || ORIG_REF_NAME==ULTRA96V2_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_PWM_w_Int_1_0/ULTRA96V2_PWM_w_Int_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_PWM_w_Int_1_0 || ORIG_REF_NAME==ULTRA96V2_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_system_management_wiz_0_0/ULTRA96V2_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_system_management_wiz_0_0 || ORIG_REF_NAME==ULTRA96V2_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlconcat_0_0/ULTRA96V2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlconcat_0_0 || ORIG_REF_NAME==ULTRA96V2_xlconcat_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_0_0/ULTRA96V2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_0_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_1_0/ULTRA96V2_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_1_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_1_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_2_0/ULTRA96V2_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_2_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_2_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_3_0/ULTRA96V2_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_3_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_3_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_4_0/ULTRA96V2_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_4_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_4_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_5_0/ULTRA96V2_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_5_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_5_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_6_0/ULTRA96V2_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_6_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_6_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_7_0/ULTRA96V2_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_7_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_7_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_8_0/ULTRA96V2_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_8_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_8_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlslice_9_0/ULTRA96V2_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlslice_9_0 || ORIG_REF_NAME==ULTRA96V2_xlslice_9_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_axi_intc_0_0/ULTRA96V2_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_axi_intc_0_0 || ORIG_REF_NAME==ULTRA96V2_axi_intc_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlconcat_interrupt_0_0/ULTRA96V2_xlconcat_interrupt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlconcat_interrupt_0_0 || ORIG_REF_NAME==ULTRA96V2_xlconcat_interrupt_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_xlconstant_gnd_0/ULTRA96V2_xlconstant_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_xlconstant_gnd_0 || ORIG_REF_NAME==ULTRA96V2_xlconstant_gnd_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_clk_wiz_0_0/ULTRA96V2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_clk_wiz_0_0 || ORIG_REF_NAME==ULTRA96V2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_0_1/ULTRA96V2_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_0_1 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_1_0/ULTRA96V2_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_1_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_2_0/ULTRA96V2_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_2_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_3_0/ULTRA96V2_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_3_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_4_0/ULTRA96V2_proc_sys_reset_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_4_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_5_0/ULTRA96V2_proc_sys_reset_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_5_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_proc_sys_reset_6_0/ULTRA96V2_proc_sys_reset_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_proc_sys_reset_6_0 || ORIG_REF_NAME==ULTRA96V2_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_0/ULTRA96V2_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_0 || ORIG_REF_NAME==ULTRA96V2_auto_ds_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_0/ULTRA96V2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_0 || ORIG_REF_NAME==ULTRA96V2_auto_pc_0} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_1/ULTRA96V2_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_1 || ORIG_REF_NAME==ULTRA96V2_auto_ds_1} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_1/ULTRA96V2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_1 || ORIG_REF_NAME==ULTRA96V2_auto_pc_1} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_2/ULTRA96V2_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_2 || ORIG_REF_NAME==ULTRA96V2_auto_ds_2} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_2/ULTRA96V2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_2 || ORIG_REF_NAME==ULTRA96V2_auto_pc_2} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_3/ULTRA96V2_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_3 || ORIG_REF_NAME==ULTRA96V2_auto_ds_3} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_3/ULTRA96V2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_3 || ORIG_REF_NAME==ULTRA96V2_auto_pc_3} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_4/ULTRA96V2_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_4 || ORIG_REF_NAME==ULTRA96V2_auto_ds_4} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_4/ULTRA96V2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_4 || ORIG_REF_NAME==ULTRA96V2_auto_pc_4} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_5/ULTRA96V2_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_5 || ORIG_REF_NAME==ULTRA96V2_auto_ds_5} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_5/ULTRA96V2_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_5 || ORIG_REF_NAME==ULTRA96V2_auto_pc_5} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_6/ULTRA96V2_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_6 || ORIG_REF_NAME==ULTRA96V2_auto_ds_6} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_6/ULTRA96V2_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_6 || ORIG_REF_NAME==ULTRA96V2_auto_pc_6} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_7/ULTRA96V2_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_7 || ORIG_REF_NAME==ULTRA96V2_auto_ds_7} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_7/ULTRA96V2_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_7 || ORIG_REF_NAME==ULTRA96V2_auto_pc_7} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_ds_8/ULTRA96V2_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_ds_8 || ORIG_REF_NAME==ULTRA96V2_auto_ds_8} -quiet] -quiet

# IP: bd/ULTRA96V2/ip/ULTRA96V2_auto_pc_8/ULTRA96V2_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ULTRA96V2_auto_pc_8 || ORIG_REF_NAME==ULTRA96V2_auto_pc_8} -quiet] -quiet

# XDC: bd/ULTRA96V2/ULTRA96V2_ooc.xdc
